### ISSUE TITLE
Assignment 4 some variables not defined

### ISSUE THREAD

**Issue by wfz0755** [cuhkrlcourse/ierg5350-assignment#17]
In the block where we are asked to implement ppo, it seems that in line 
```torch.save(network.state_dict(),args.env_name.split('-')[0]+'/CheckPoints/checkpoint_new_{0}hidden_{1}drop_prob_{2}repeat'.format(args.hid_num,config.drop_prob,repeat))```
and 
```np.savetxt(args.env_name.split('-')[0]+'/Rwds/rwds_new_{0}hidden_{1}drop_prob_{2}repeat'.format(args.hid_num,config.drop_prob,repeat),rwds)```, 
both "config" and "repeat" are not defined. Due to this, errors will be prompted. So should we assume that "config" should be replaced by "args" and "repeat" can simply be deleted?

**Comment by 2Groza** [comment]
Yes, you are right. The variables drop_prob and repeat are only used for recording the training results and will not affect the results.

You can just name them in your way.

> In the block where we are asked to implement ppo, it seems that in line
> `torch.save(network.state_dict(),args.env_name.split('-')[0]+'/CheckPoints/checkpoint_new_{0}hidden_{1}drop_prob_{2}repeat'.format(args.hid_num,config.drop_prob,repeat))`
> and
> `np.savetxt(args.env_name.split('-')[0]+'/Rwds/rwds_new_{0}hidden_{1}drop_prob_{2}repeat'.format(args.hid_num,config.drop_prob,repeat),rwds)`,
> both "config" and "repeat" are not defined. Due to this, errors will be prompted. So should we assume that "config" should be replaced by "args" and "repeat" can simply be deleted?

**Comment by wfz0755** [comment]
Got it, thanks!
